In [1]:
import numpy as np

# Define a 4x4 matrix
I = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

X = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, -1, 0],
    [0, 0, 0, -1]
])

Y = np.array([
    [1, 0, 0, 0],
    [0, -1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, -1]
])

Z = np.array([
    [1, 0, 0, 0],
    [0, -1, 0, 0],
    [0, 0, -1, 0],
    [0, 0, 0, 1]
])


II=np.kron(X, X)
print(II)

[[ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]]


In [18]:
import sympy as sp

# Define the symbolic variable p
p = sp.symbols('p')

# Define the symbolic variables for eta values
eta1, eta2, eta3, eta4, eta5, eta6, eta7, eta8, eta9, eta10, eta11, eta12, eta13, eta14, eta15, eta16 = sp.symbols('eta1 eta2 eta3 eta4 eta5 eta6 eta7 eta8 eta9 eta10 eta11 eta12 eta13 eta14 eta15 eta16')
D2_inv = diagonal_matrix = np.diag([1,1/(1-p),1/(1-p),1/(1-p),1/(1-p),1/(1-p),1/(1-p),1/(1-p),1/(1-p),1/(1-p),1/(1-p),
                                    1/(1-p),1/(1-p),1/(1-p),1/(1-p),1/(1-p)])
print(D2_inv)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1/(1 - p) 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1/(1 - p) 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1/(1 - p) 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1/(1 - p) 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1/(1 - p) 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1/(1 - p) 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1/(1 - p) 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1/(1 - p) 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1/(1 - p) 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1/(1 - p) 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1/(1 - p) 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1/(1 - p) 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1/(1 - p) 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1/(1 - p) 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1/(1 - p)]]


In [19]:
m1 = np.diag(np.kron(I, I))
m2 = np.diag(np.kron(I, X))
m3 = np.diag(np.kron(I, Y))
m4 = np.diag(np.kron(I, Z))
m5 = np.diag(np.kron(X, I))
m6 = np.diag(np.kron(X, X))
m7 = np.diag(np.kron(X, Y))
m8 = np.diag(np.kron(X, Z))
m9 = np.diag(np.kron(Y, I))
m10 = np.diag(np.kron(Y, X))
m11 = np.diag(np.kron(Y, Y))
m12 = np.diag(np.kron(Y, Z))
m13 = np.diag(np.kron(Z, I))
m14 = np.diag(np.kron(Z, X))
m15 = np.diag(np.kron(Z, Y))
m16 = np.diag(np.kron(Z, Z))

In [22]:
# Set up the system of equations as Ax = B
A = sp.Matrix([m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,m16]).T
B = np.diag(D2_inv)
B = sp.Matrix(B)

In [23]:
# Solve for the coefficients eta1, eta2, eta3, eta4
#etas = np.linalg.solve(A, B)
solution = sp.linsolve((A, B), eta1, eta2, eta3, eta4,eta5, eta6, eta7, eta8, eta9, eta10, eta11, eta12, eta13, eta14, eta15, eta16)
print(solution)

{((p - 16)/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16), p/(16*p - 16))}


Overhead

In [26]:
1*(16-p)/(16-16*p) + 15*p/(16-16*p)

15*p/(16 - 16*p) + (16 - p)/(16 - 16*p)